Shop/Areas/Admin/Models/Image.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Areas.Admin.Models
{
    public class Image
    {
        public int Id { get; set; }
        public int IdProduct { get; set; }
        public string Name { get; set; }

        [ForeignKey("IdProduct")]
        public virtual Product product { get; set; }
    }
}

Shop/Areas/Admin/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shop.Areas.Admin.Data;
using Shop.Areas.Admin.Models;

namespace Shop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ImagesController : Controller
    {
        private readonly DPContext _context;

        public ImagesController(DPContext context)
        {
            _context = context;
        }

        // GET: Admin/Images
        public async Task<IActionResult> Index(string searchString)
        {
            var movies = from m in _context.Image.Include(i => i.product) select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.product.Name.Contains(searchString));

            }
            ViewData["IdProduct"] = new SelectList(_context.product, "Id", "Name");
            return View(await movies.ToListAsync());

            //var dPContext = _context.Image.Include(i => i.product);
            //return View(await dPContext.ToListAsync());
        }

        // GET: Admin/Images/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image
                .Include(i => i.product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        // GET: Admin/Images/Create
        public IActionResult Create()
        {
            ViewData["IdProduct"] = new SelectList(_context.product, "Id", "Name");
            return View();
        }

        // POST: Admin/Images/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdProduct,Name")] Image image, IFormFile ful)
        {
            if (ModelState.IsValid)
            {
                _context.Add(image);
                await _context.SaveChangesAsync();
                var path = Path.Combine(
                    Directory.GetCurrentDirectory(), "wwwroot/images/products", image.Id + "." + ful.FileName.Split(".")[ful.FileName.Split(".").Length - 1]);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await ful.CopyToAsync(stream);
                }
                image.Name = image.Id + "." + ful.FileName.Split(".")[ful.FileName.Split(".").Length - 1];
                _context.Update(image);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdProduct"] = new SelectList(_context.product, "Id", "Id", image.IdProduct);
            return View(image);
        }


        // GET: Admin/Images/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image.FindAsync(id);
            if (image == null)
            {
                return NotFound();
            }
            ViewData["IdProduct"] = new SelectList(_context.product, "Id", "Id", image.IdProduct);
            return View(image);
        }

        // POST: Admin/Images/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdProduct,Name")] Image image, IFormFile ful)
        {
            if (id != image.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (ful != null)
                    {
                        string t = image.Id + "." + ful.FileName.Split(".")[ful.FileName.Split(".").Length - 1];
                        var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/products", image.Name);
                        if (System.IO.File.Exists(path))
                        {
                            System.IO.File.Delete(path);
                        }
                        path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/products", t);
                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await ful.CopyToAsync(stream);
                        }
                        image.Name = t;
                        _context.Update(image);
                        await _context.SaveChangesAsync();

                    }
                    else
                    {
                        _context.Update(image);
                        await _context.SaveChangesAsync();
                    }

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImageExists(image.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdProduct"] = new SelectList(_context.product, "Id", "Id", image.IdProduct);
            return View(image);
        }

        // GET: Admin/Images/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image
                .Include(i => i.product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        // POST: Admin/Images/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var image = await _context.Image.FindAsync(id);
            _context.Image.Remove(image);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ImageExists(int id)
        {
            return _context.Image.Any(e => e.Id == id);
        }
    }
}

Shop/Areas/Admin/Views/Images/Create.cshtml
@model Shop.Areas.Admin.Models.Image

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Image</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdProduct" class="control-label"></label>
                <select asp-for="IdProduct" class="form-control" asp-items="ViewBag.IdProduct"></select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="ful" name="ful">
                    <label class="custom-file-label" for="ful">Choose File</label>
                </div>
                <div class="form-group">
                    <img id="Name" src="~/images/noimage.jpg" alt="no image" class="img-thumbnail">
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
    function readURL(input, img) {
        if (input.files && input.files[0]){
            var reader = new FileReader();
            reader.onload = function (e) {
                $('img').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#ful").change(function () {
        readURL(this,'#img');
    })
    </script>
}

Shop/Areas/Admin/Views/Images/Delete.cshtml
@model Shop.Areas.Admin.Models.Image

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Image</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.product)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.product.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Shop/Areas/Admin/Views/Images/Details.cshtml
@model Shop.Areas.Admin.Models.Image

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Image</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.product)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.product.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Shop/Areas/Admin/Views/Images/Edit.cshtml
@model Shop.Areas.Admin.Models.Image

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Image</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="IdProduct" class="control-label"></label>
                <select asp-for="IdProduct" class="form-control" asp-items="ViewBag.IdProduct"></select>
                <span asp-validation-for="IdProduct" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="ful" name="ful">
                    <label class="custom-file-label" for="ful">Choose File</label>
                </div>
                <div class="form-group">
                    <img id="Image" src="~/images/products/@Model.Name" class="img-thumbnail">
                    <input asp-for="Name" hidden />
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
    function readURL(input, img) {
        if (input.files && input.files[0]){
            var reader = new FileReader();
            reader.onload = function (e) {
                $('img').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#ful").change(function () {
        readURL(this,'#img');
    })
    </script>
}

Shop/Areas/Admin/Views/Images/Index.cshtml
@model IEnumerable<Shop.Areas.Admin.Models.Image>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>
<form asp-controller="Images" asp-action="Index" method="get">
    <p>
        Tên sản phẩm:<input type="text" name="searchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.product.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>